# File: app_helpers/labels.py
from typing import Dict

GROUP_LABELS: Dict[str, str] = {
     "SAW": "OP10A Saw Bar to Billet Length",
     "IH": "OP20A Induction Heat for Forging",
     "P": "OP30A Forging",
     "CL": "OP40A Saw Cavity to Length",
     "CC": "OP50A Clean Cavity",
     "ROD": "OP60A Machine Pre-Nose Profile External",
     "RID": "OP65A Machine Pre Nose Profile Internal",
     "BR": "OP66A Machine Base Recess Groove for Heat Treatment",
     "WC": "OP67A Weigh & Categorize Shells",
     "GR": "OP70A Apply Graphite",
     "NIH": "OP80A Induction Heating for Nosing",
     "NP": "OP90A Nosing",
     "RNB": "OP110A Rough Nose Bore, Face & External Chamfer",
     "PO": "OP120A Pre Machine Ogive for Heat Treatment",
     "HT": "OP170A Heat Treatment",
     "SPHDT": "OP180A Surface Preparation for Hardness Test",
     "HDT": "OP190A Hardness Test",
     "CUT": "OP200A Saw Tensile Test Pieces",
     "MTT": "OP210A Machine Tensile Test Pieces",
     "TT": "OP220A Tensile Test",
     "HS": "OP230A Hard Stamp Heat Code & Shell Number",
     "FO": "OP280A Final Machine Ogive",
     "UT": "OP290A Ultrasonic Test",
     "SR": "OP300A Stamping Roller Marking",
     "DB": "OP302A Drill Base, Rough Machine Bore for Exapandable Mandrel & Machine Driving Band Groove",
     "KN": "OP320A Knurling",
     "PDB": "OP340A Press on Driving Band",
     "FC": "OP380A Final Machine Cavity",
     "SP": "OP390A Spooning", 
     "RG": "OP395A Roller Grind Blend Out Step",
     "SB": "OP400A Shot Blast Cavity",
     "NT": "OP410A Final Machine Nose Thread",
     "BT": "OP420A Final Machine Driving Band & Base Thread",
     "MP": "OP425A Magnetic Particle Test",
     "FB": "OP430A Final Balancing",
     "FI": "OP440A Final Inspection",
     "D&P": "OP450A Apply Rust Preventative and Palletise",   
}


MACHINE_LABELS: Dict[str, str] = {
    "SAW1": "Billet Cut 1",
    "SAW2": "Billet Cut 2",
    "SAW3": "Billet Cut 3",
    "SAW4": "Billet Cut 4",
    "SAW5": "Billet Cut 5",
    "SAW6": "Billet Cut 6",
    "SAW7": "Billet Cut 7",
    "SAW8": "Billet Cut 8",
    "SAW9": "Billet Cut 9",
    "IH1": "Induction Heater 1",
    "IH2": "Induction Heater 2",
    "IH3": "Induction Heater 3",
    "P1": "Press 1",
    "P2": "Press 2",
    "CL1": "Cut to Length 1", 
    "CL2": "Cut to Length 2", 
    "CL3": "Cut to Length 3", 
    "CL4": "Cut to Length 4", 
    "CL5": "Cut to Length 5", 
    "CL6": "Cut to Length 6", 
    "CL7": "Cut to Length 7", 
    "CL8": "Cut to Length 8", 
    "CC1": "Shotblast 1", 
    "CC2": "Shotblast 2", 
    "CC3": "Shotblast 3", 
    "CC4": "Shotblast 4", 
    "SB1": "Shotblast 5", 
    "SB2": "Shotblast 6", 
    "SB3": "Shotblast 7", 
    "SB4": "Shotblast 8", 
    "SB5": "Shotblast 9", 
    "SB6": "Shotblast 10", 
    "SB7": "Shotblast 11", 
    "SB8": "Shotblast 12", 
    "SB9": "Shotblast 13", 
    "SB10": "Shotblast 14", 
    "ROD1": "Rough OD 1",
    "ROD2": "Rough OD 2",
    "ROD3": "Rough OD 3",
    "ROD4": "Rough OD 4",
    "ROD5": "Rough OD 5",
    "ROD6": "Rough OD 6",
    "ROD7": "Rough OD 7",
    "ROD8": "Rough OD 8",
    "ROD9": "Rough OD 9",
    "ROD10": "Rough OD 10",
    "RID1": "Rough ID 1", 
    "RID2": "Rough ID 2",
    "RID3": "Rough ID 3",
    "RID4": "Rough ID 4",
    "RID5": "Rough ID 5",
    "RID6": "Rough ID 6",
    "BR1": "Base Recess 1", 
    "BR2": "Base Recess 2", 
    "BR3": "Base Recess 3", 
    "BR4": "Base Recess 4", 
    "BR5": "Base Recess 5", 
    "BR6": "Base Recess 6", 
    "WC": "Weigh and Categorise Process", 
    "GR": "Apply Graphite Process",
    "NIH1": "Nosing Induction Heater 1", 
    "NIH2": "Nosing Induction Heater 2",
    "NP1": "Nosing Press 1", 
    "NP2": "Nosing Press 2", 
    "RNB1": "Rough Nose Bore 1", 
    "RNB2": "Rough Nose Bore 2", 
    "RNB3": "Rough Nose Bore 3", 
    "RNB4": "Rough Nose Bore 4", 
    "PO1": "Pre Ogive 1",
    "PO2": "Pre Ogive 2",
    "PO3": "Pre Ogive 3",
    "PO4": "Pre Ogive 4",
    "PO5": "Pre Ogive 5",
    "PO6": "Pre Ogive 6",
    "HT": "Heat Treatment", 
    "SPHDT1": "Milling Machine 1", 
    "SPHDT2": "Milling Machine 2", 
    "HDT1": "Hardness Tester 1", 
    "HDT2": "Hardness Tester 2", 
    "CUT1": "Cut to Length 1", 
    "CUT2": "Cut to Length 2", 
    "CUT3": "Cut to Length 3", 
    "CUT4": "Cut to Length 4", 
    "MTT1": "Machine 1", 
    "MTT2": "Machine 2", 
    "TT1": "Tensile Tester 1",
    "TT2": "Tensile Tester 2", 
    "HS1": "Hard Stamper 1", 
    "HS2": "Hard Stamper 2", 
    "FO1": "Final Ogive 1",
    "FO2": "Final Ogive 2",
    "FO3": "Final Ogive 3",
    "FO4": "Final Ogive 4",
    "FO5": "Final Ogive 5",
    "FO6": "Final Ogive 6",
    "FO7": "Final Ogive 7",
    "FO8": "Final Ogive 8",
    "UT1": "Ultrasonic Tester 1", 
    "UT2": "Ultrasonic Tester 2", 
    "SR1": "Roller Stamp 1", 
    "SR2": "Roller Stamp 2", 
    "DB1": "Drill Base 1",
    "DB2": "Drill Base 2",
    "DB3": "Drill Base 3",
    "DB4": "Drill Base 4",
    "DB5": "Drill Base 5",
    "DB6": "Drill Base 6",
    "DB7": "Drill Base 7",
    "DB8": "Drill Base 8",
    "DB9": "Drill Base 9",
    "DB10": "Drill Base 10",
    "DB11": "Drill Base 11",
    "DB12": "Drill Base 12",
    "KN1": "Knurling Machine 1",
    "KN2": "Knurling Machine 2",
    "KN3": "Knurling Machine 3",
    "KN4": "Knurling Machine 4",
    "PDB1": "Banding Machine 1",
    "PDB2": "Banding Machine 2",
    "PDB3": "Banding Machine 3",
    "PDB4": "Banding Machine 4",
    "FC1": "Final Cavity 1",
    "FC2": "Final Cavity 2",
    "FC3": "Final Cavity 3",
    "FC4": "Final Cavity 4",
    "FC5": "Final Cavity 5",
    "FC6": "Final Cavity 6",
    "SP1": "Spooning Machine 1", 
    "SP2": "Spooning Machine 2", 
    "RG1": "Roller Grinder 1", 
    "RG2": "Roller Grinder 2", 
    "RG3": "Roller Grinder 3", 
    "RG4": "Roller Grinder 4", 
    "RG5": "Roller Grinder 5", 
    "RG6": "Roller Grinder 6",     
    "RG7": "Roller Grinder 7", 
    "RG8": "Roller Grinder 8", 
    "RG9": "Roller Grinder 9",     
    "RG10": "Roller Grinder 10", 
    "RG11": "Roller Grinder 11", 
    "RG12": "Roller Grinder 12", 
    "NT1": "Nose Threads 1", 
    "NT2": "Nose Threads 2",
    "NT3": "Nose Threads 3",
    "NT4": "Nose Threads 4",
    "NT5": "Nose Threads 5",
    "NT6": "Nose Threads 6",
    "BT1": "Base Threads 1",
    "BT2": "Base Threads 2",
    "BT3": "Base Threads 3",
    "BT4": "Base Threads 4",
    "BT5": "Base Threads 5",
    "BT6": "Base Threads 6",
    "MP1": "MPI 1",
    "MP2": "MPI 2",
    "MP3": "MPI 3",
    "MP4": "MPI 4",
    "FB1": "Final Balancing 1",
    "FB2": "Final Balancing 2",
    "FB3": "Final Balancing 3",
    "FB4": "Final Balancing 4",
    "FI1": "Final Inspection Station 1", 
    "FI2": "Final Inspection Station 2", 
    "FI3": "Final Inspection Station 3", 
    "FI4": "Final Inspection Station 4", 
    "D&P1": "Dip & Pack 1", 
    "D&P2": "Dip & Pack 2", 
    "D&P3": "Dip & Pack 3", 
    "D&P4": "Dip & Pack 4",
}
    
NODE_LABELS: Dict[str, str] = {
    "WIPi_SAW": "Incoming Billets",
    "WIPo_SAW1": "Billet Cut 1 Outgoing",
    "WIPo_SAW2": "Billet Cut 2 Outgoing",
    "WIPo_SAW3": "Billet Cut 3 Outgoing",
    "WIPo_SAW4": "Billet Cut 4 Outgoing",
    "WIPo_SAW5": "Billet Cut 5 Outgoing",
    "WIPo_SAW6": "Billet Cut 6 Outgoing",
    "WIPo_SAW7": "Billet Cut 7 Outgoing",
    "WIPo_SAW8": "Billet Cut 8 Outgoing",
    "WIPo_SAW9": "Billet Cut 9 Outgoing",
    "WIPi_IH1": "Induction Heater 1 Incoming",
    "WIPi_IH2": "Induction Heater 2 Incoming",
    "WIPi_IH3": "Induction Heater 3 Incoming",
    "WIPo_IH1": "Induction Heater 1 Outgoing",
    "WIPo_IH2": "Induction Heater 2 Outgoing",
    "WIPo_IH3": "Induction Heater 3 Outgoing",
    "WIPi_CL": "Cut to Length Incoming",
    "WIPo_CL": "Cut to Length Outgoing",
    "WIPi_CC1": "Clean Cavity 1 Incoming",
    "WIPi_CC2": "Clean Cavity 2 Incoming",
    "WIPi_CC3": "Clean Cavity 3 Incoming",
    "WIPi_CC4": "Clean Cavity 4 Incoming",
    "WIPo_CC1": "Clean Cavity 1 Outgoing",
    "WIPo_CC2": "Clean Cavity 2 Outgoing",
    "WIPo_CC3": "Clean Cavity 3 Outgoing",
    "WIPo_CC4": "Clean Cavity 4 Outgoing",
    "finished_goods": "Cell 1 WIP Area",
    "WIPo_GantryIn": "Gantry Incoming",
    "WIPo_GantryConv": "Gantry Outgoing",
    "WIPi_ROD": "Rough OD Incoming",
    "WIPo_ROD1": "Rough OD 1 Outgoing",
    "WIPo_ROD2": "Rough OD 2 Outgoing",
    "WIPo_ROD3": "Rough OD 3 Outgoing",
    "WIPo_ROD4": "Rough OD 4 Outgoing",
    "WIPo_ROD5": "Rough OD 5 Outgoing",
    "WIPo_ROD6": "Rough OD 6 Outgoing",
    "WIPo_ROD7": "Rough OD 7 Outgoing",
    "WIPo_ROD8": "Rough OD 8 Outgoing",
    "WIPo_ROD9": "Rough OD 9 Outgoing",
    "WIPo_ROD10": "Rough OD 10 Outgoing",
    "WIPi_RID1": "Rough ID 1 Incoming",
    "WIPi_RID2": "Rough ID 2 Incoming",
    "WIPi_RID3": "Rough ID 3 Incoming",
    "WIPi_RID4": "Rough ID 4 Incoming",
    "WIPi_RID5": "Rough ID 5 Incoming",
    "WIPi_RID6": "Rough ID 6 Incoming",
    "WIPo_RID1": "Rough ID 1 Outgoing",
    "WIPo_RID2": "Rough ID 2 Outgoing",
    "WIPo_RID3": "Rough ID 3 Outgoing",
    "WIPo_RID4": "Rough ID 4 Outgoing",
    "WIPo_RID5": "Rough ID 5 Outgoing",
    "WIPo_RID6": "Rough ID 6 Outgoing",
    "WIPi_BR1": "Base Recess 1 Incoming",
    "WIPi_BR2": "Base Recess 2 Incoming",
    "WIPi_BR3": "Base Recess 3 Incoming",
    "WIPi_BR4": "Base Recess 4 Incoming",
    "WIPi_BR5": "Base Recess 5 Incoming",
    "WIPi_BR6": "Base Recess 6 Incoming",
    "WIPo_BR1": "Base Recess 1 Outgoing",
    "WIPo_BR2": "Base Recess 2 Outgoing",
    "WIPo_BR3": "Base Recess 3 Outgoing",
    "WIPo_BR4": "Base Recess 4 Outgoing",
    "WIPo_BR5": "Base Recess 5 Outgoing",
    "WIPo_BR6": "Base Recess 6 Outgoing",
    "finished_goods2": "Cell 2 WIP Area",
    "WIPi_WC": "Weigh & Classify Incoming",
    "WIPo_WC": "Weigh & Classify Outgoing",
    "WIPi_GR": "Apply Graphite Incoming",
    "WIPo_GR": "Apply Graphite Outgoing",
    "WIPo_NP": "Nosing Outgoing",
    "WIPi_RNB1": "Rough Nose Bore 1 Incoming",
    "WIPi_RNB2": "Rough Nose Bore 2 Incoming",
    "WIPi_RNB3": "Rough Nose Bore 3 Incoming",
    "WIPi_RNB4": "Rough Nose Bore 4 Incoming",
    "WIPo_RNB1": "Rough Nose Bore 1 Outgoing",
    "WIPo_RNB2": "Rough Nose Bore 2 Outgoing",
    "WIPo_RNB3": "Rough Nose Bore 3 Outgoing",
    "WIPo_RNB4": "Rough Nose Bore 4 Outgoing",
    "finished_goods3": "Rough Nose Bore Completed",
    "WIPi_PO1": "Pre-Ogive 1 Incoming",
    "WIPi_PO2": "Pre-Ogive 2 Incoming",
    "WIPi_PO3": "Pre-Ogive 3 Incoming",
    "WIPi_PO4": "Pre-Ogive 4 Incoming",
    "WIPi_PO5": "Pre-Ogive 5 Incoming",
    "WIPi_PO6": "Pre-Ogive 6 Incoming",
    "WIPo_PO1": "Pre-Ogive 1 Outgoing",
    "WIPo_PO2": "Pre-Ogive 2 Outgoing",
    "WIPo_PO3": "Pre-Ogive 3 Outgoing",
    "WIPo_PO4": "Pre-Ogive 4 Outgoing",
    "WIPo_PO5": "Pre-Ogive 5 Outgoing",
    "WIPo_PO6": "Pre-Ogive 6 Outgoing",
    "WIPi_HT": "Heat Treatment Incoming",
    "WIPo_HT": "Heat Treatment Outgoing",
    "WIPi_SPHDT": "Surface Prep for Hardness Test Incoming",
    "WIPi_HDT1": "Hardness Tester 1 Incoming",
    "WIPi_HDT2": "Hardness Tester 2 Incoming",
    "WIPo_HDT": "Hardness Tester 2 Outgoing",
    "test_feed": "Destructive Testing",
    "scrap": "Scrap", 
    "WIPi_CUT": "Cut Tensile Pieces Incoming", 
    "WIPo_CUT": "Cut Tensile Pieces Outgoing", 
    "WIPi_MTT1": "Machine Tensile Test Pieces 1 Incoming", 
    "WIPo_MTT1": "Machine Tensile Test Pieces 1 Outgoing", 
    "WIPi_MTT2": "Machine Tensile Test Pieces 2 Incoming", 
    "WIPo_MTT2": "Machine Tensile Test Pieces 2 Outgoing", 
    "WIPi_TT1": "Tensile Test 1 Incoming", 
    "WIPo_TT1": "Tensile Test 1 Outgoing", 
    "WIPi_TT2": "Tensile Test 2 Incoming", 
    "WIPo_TT2": "Tensile Test 2 Outgoing", 
    "hold": "Tensile Testing Holding Area", 
    "WIPi_HS": "Hard Stamping Incoming", 
    "WIPo_HS": "Hard Stamping Outgoing", 
    "finished_goods4": "Cell 4 Incoming WIP Area", 
    "WIPi_FO1": "Final-Ogive 1 Incoming",
    "WIPi_FO2": "Final-Ogive 2 Incoming",
    "WIPi_FO3": "Final-Ogive 3 Incoming",
    "WIPi_FO4": "Final-Ogive 4 Incoming",
    "WIPi_FO5": "Final-Ogive 5 Incoming",
    "WIPi_FO6": "Final-Ogive 6 Incoming",
    "WIPi_FO7": "Final-Ogive 7 Incoming",
    "WIPi_FO8": "Final-Ogive 8 Incoming",
    "WIPo_FO1": "Final-Ogive 1 Outgoing",
    "WIPo_FO2": "Final-Ogive 2 Outgoing",
    "WIPo_FO3": "Final-Ogive 3 Outgoing",
    "WIPo_FO4": "Final-Ogive 4 Outgoing",
    "WIPo_FO5": "Final-Ogive 5 Outgoing",
    "WIPo_FO6": "Final-Ogive 6 Outgoing",
    "WIPo_FO7": "Final-Ogive 7 Outgoing",
    "WIPo_FO8": "Final-Ogive 8 Outgoing",
    "WIPi_UT": "Ultrasonic Incoming",
    "WIPo_UT": "Ultrasonic Outgoing",
    "WIPi_SR": "Roller Stamping Incoming",
    "WIPo_SR": "Roller Stamping Outgoing",
    "WIPi_DB1": "Drill Base 1 Incoming",
    "WIPi_DB2": "Drill Base 2 Incoming",
    "WIPi_DB3": "Drill Base 3 Incoming",
    "WIPi_DB4": "Drill Base 4 Incoming",
    "WIPi_DB5": "Drill Base 5 Incoming",
    "WIPi_DB6": "Drill Base 6 Incoming",
    "WIPi_DB7": "Drill Base 7 Incoming",
    "WIPi_DB8": "Drill Base 8 Incoming",
    "WIPi_DB9": "Drill Base 9 Incoming",
    "WIPi_DB10": "Drill Base 10 Incoming",
    "WIPi_DB11": "Drill Base 11 Incoming",
    "WIPi_DB12": "Drill Base 12 Incoming",
    "WIPo_DB1": "Drill Base 1 Outgoing",
    "WIPo_DB2": "Drill Base 2 Outgoing",
    "WIPo_DB3": "Drill Base 3 Outgoing",
    "WIPo_DB4": "Drill Base 4 Outgoing",
    "WIPo_DB5": "Drill Base 5 Outgoing",
    "WIPo_DB6": "Drill Base 6 Outgoing",
    "WIPo_DB7": "Drill Base 7 Outgoing",
    "WIPo_DB8": "Drill Base 8 Outgoing",
    "WIPo_DB9": "Drill Base 9 Outgoing",
    "WIPo_DB10": "Drill Base 10 Outgoing",
    "WIPo_DB11": "Drill Base 11 Outgoing",
    "WIPo_DB12": "Drill Base 12 Outgoing",
    "WIPi_KN": "Knurling Incoming", 
    "WIPo_KN": "Knurling Outgoing", 
    "WIPi_PDB1": "Banding 1 Incoming", 
    "WIPi_PDB2": "Banding 2 Incoming", 
    "WIPi_PDB3": "Banding 3 Incoming", 
    "WIPi_PDB4": "Banding 4 Incoming", 
    "WIPo_PDB1": "Banding 1 Outgoing", 
    "WIPo_PDB2": "Banding 2 Outgoing", 
    "WIPo_PDB3": "Banding 3 Outgoing", 
    "WIPo_PDB4": "Banding 4 Outgoing", 
    "WIPi_FC1": "Final Cavity 1 Incoming", 
    "WIPi_FC2": "Final Cavity 2 Incoming", 
    "WIPi_FC3": "Final Cavity 3 Incoming", 
    "WIPi_FC4": "Final Cavity 4 Incoming", 
    "WIPi_FC5": "Final Cavity 5 Incoming", 
    "WIPi_FC6": "Final Cavity 6 Incoming",
    "WIPo_FC1": "Final Cavity 1 Outgoing", 
    "WIPo_FC2": "Final Cavity 2 Outgoing", 
    "WIPo_FC3": "Final Cavity 3 Outgoing", 
    "WIPo_FC4": "Final Cavity 4 Outgoing", 
    "WIPo_FC5": "Final Cavity 5 Outgoing", 
    "WIPo_FC6": "Final Cavity 6 Outgoing",
    "WIPi_SP1": "Spooning 1 Incoming", 
    "WIPo_SP1": "Spooning 1 Outgoing", 
    "WIPi_SP2": "Spooning 2 Incoming", 
    "WIPo_SP2": "Spooning 2 Outgoing", 
    "finished_goods5": "Spooning Outgoing Buffer",
    "WIPi_RG": "Roller Grinding Incoming",  
    "WIPo_RG": "Roller Grinding Outgoing", 
    "WIPi_SB1": "Shot Blast 5 Incoming", 
    "WIPi_SB2": "Shot Blast 6 Incoming",
    "WIPi_SB3": "Shot Blast 7 Incoming",
    "WIPi_SB4": "Shot Blast 8 Incoming",
    "WIPi_SB5": "Shot Blast 9 Incoming",
    "WIPi_SB6": "Shot Blast 10 Incoming",
    "WIPi_SB7": "Shot Blast 11 Incoming",
    "WIPi_SB8": "Shot Blast 12 Incoming",
    "WIPi_SB9": "Shot Blast 13 Incoming",
    "WIPi_SB10": "Shot Blast 14 Incoming",
    "WIPo_SB1": "Shot Blast 5 Outgoing", 
    "WIPo_SB2": "Shot Blast 6 Outgoing",
    "WIPo_SB3": "Shot Blast 7 Outgoing",
    "WIPo_SB4": "Shot Blast 8 Outgoing",
    "WIPo_SB5": "Shot Blast 9 Outgoing",
    "WIPo_SB6": "Shot Blast 10 Outgoing",
    "WIPo_SB7": "Shot Blast 11 Outgoing",
    "WIPo_SB8": "Shot Blast 12 Outgoing",
    "WIPo_SB9": "Shot Blast 13 Outgoing",
    "WIPo_SB10": "Shot Blast 14 Outgoing",
    "WIPi_NT1": "Nose Threads 1 Incoming",
    "WIPi_NT2": "Nose Threads 2 Incoming",
    "WIPi_NT3": "Nose Threads 3 Incoming",
    "WIPi_NT4": "Nose Threads 4 Incoming",
    "WIPi_NT5": "Nose Threads 5 Incoming",
    "WIPi_NT6": "Nose Threads 6 Incoming",
    "WIPo_NT1": "Nose Threads 1 Outgoing",
    "WIPo_NT2": "Nose Threads 2 Outgoing",
    "WIPo_NT3": "Nose Threads 3 Outgoing",
    "WIPo_NT4": "Nose Threads 4 Outgoing",
    "WIPo_NT5": "Nose Threads 5 Outgoing",
    "WIPo_NT6": "Nose Threads 6 Outgoing",
    "WIPi_BT1": "Base Threads 1 Incoming", 
    "WIPi_BT2": "Base Threads 2 Incoming", 
    "WIPi_BT3": "Base Threads 3 Incoming", 
    "WIPi_BT4": "Base Threads 4 Incoming", 
    "WIPi_BT5": "Base Threads 5 Incoming", 
    "WIPi_BT6": "Base Threads 6 Incoming", 
    "WIPo_BT1": "Base Threads 1 Outgoing", 
    "WIPo_BT2": "Base Threads 2 Outgoing", 
    "WIPo_BT3": "Base Threads 3 Outgoing", 
    "WIPo_BT4": "Base Threads 4 Outgoing", 
    "WIPo_BT5": "Base Threads 5 Outgoing", 
    "WIPo_BT6": "Base Threads 6 Outgoing", 
    "WIPi_MP1": "Magnetic Particle Test 1 Incoming", 
    "WIPi_MP2": "Magnetic Particle Test 2 Incoming", 
    "WIPi_MP3": "Magnetic Particle Test 3 Incoming", 
    "WIPi_MP4": "Magnetic Particle Test 4 Incoming", 
    "WIPo_MP1": "Magnetic Particle Test 1 Outgoing", 
    "WIPo_MP2": "Magnetic Particle Test 2 Outgoing", 
    "WIPo_MP3": "Magnetic Particle Test 3 Outgoing", 
    "WIPo_MP4": "Magnetic Particle Test 4 Outgoing", 
    "WIPi_FB": "Final Balancing Incoming", 
    "WIPo_FB1": "Final Balancing 1 Outgoing", 
    "WIPo_FB2": "Final Balancing 2 Outgoing", 
    "WIPo_FB3": "Final Balancing 3 Outgoing", 
    "WIPo_FB4": "Final Balancing 4 Outgoing", 
    "WIPi_FI": "Final Inspection Incoming", 
    "WIPo_FI1": "Final Inspection 1 Outgoing",     
    "WIPo_FI2": "Final Inspection 2 Outgoing",   
    "WIPo_FI3": "Final Inspection 3 Outgoing",   
    "WIPo_FI4": "Final Inspection 4 Outgoing",   
    "WIPi_D&P1": "Dip & Pack 1 Incoming",
    "WIPi_D&P2": "Dip & Pack 2 Incoming",
    "WIPi_D&P3": "Dip & Pack 3 Incoming",
    "WIPi_D&P4": "Dip & Pack 4 Incoming",
    "WIPo_D&P1": "Dip & Pack 1 Outgoing",
    "WIPo_D&P2": "Dip & Pack 2 Outgoing",
    "WIPo_D&P3": "Dip & Pack 3 Outgoing",
    "WIPo_D&P4": "Dip & Pack 4 Outgoing",
    "finished_goods6": "Dispatch"
}

    
    
    
    
    
    
    
